### ISSUE TITLE
Read Only & Required properties are improperly handled.

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/openapi-enforcer#106]
According to the OpenAPI Specification "If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only". However, error are being thrown if a required, read only property is missing from the request body.

The current work around is not marking a property as required, but that work around changes the API contract and can make it harder to integrate with APIs.

**Example Schema**:

```yaml
Pet:
  type: object
  required:
    - id
    - name
  properties:
    id:
      type: string
      readOnly: true
    name:
      type: string
```

**Request (should work, but throws error)**:

```json
{
  "name": "Bobby"
}
```
