### ISSUE TITLE
Provide a switch to report examples with non-explicitly defined properties

### ISSUE THREAD

**Issue by phillim1** [byu-oit/openapi-enforcer#132]
This is a request to provide a switch to allow the reporting of non-explicitly defined properties in an example in a Swagger definition when `additionalProperties: false` is not present.

For example, in the attached sample API, lines 79-81 contain the fields `documentType`, `documentStatus` and `documentDetails` in an `example` - these fields are not explicitly defined in the API. When this file is validated with openapi-enforcer then the fields are correctly reported as invalid because the `additionalProperties: false` is defined on line 107.

However, most of our APIs do not define the `additionalProperties` keyword and we would like to be able to report when the examples become out of synch with the explicitly defined properties. Hence, if `additionalProperties: false` is removed from line 107 then it would be great if openapi-enforcer could provide a warning that the example fields might be out of synch with the schema. Is this possible?

Note that this request is similar to [this recent comment](https://github.com/byu-oit/openapi-enforcer/issues/131#issuecomment-1024920930) on `additionalProperties` behaviour.

- [Attached file - swagger.txt](https://github.com/byu-oit/openapi-enforcer/files/7994045/swagger.txt)

**Comment by Gi60s** [comment]
Hello @phillim1 and thanks for the issue. I think you're right that it is important to add this as a warning.

Looking at the current code I could make it so that a warning is always shown for examples that have additional properties, but there are a few potential hurdles:

1. The only way to allow you to turn this on or off without it being a significant amount of work updating the library is to create a global configuration option. I might do that.
2. There will be cases when using a `discriminator` or `allOf` will cause the warning to appear even when all properties are defined via the additional schemas.

As an example, take these components:

```yaml
components:
  schemas:
    Cat:
      allOf:
      - "$ref": "#/components/schemas/Pet"
      - type: object
        properties:
          birthDate:
            type: string
            format: date
          huntingSkill:
            type: string
    Pet:
      type: object
      required:
      - petType
      discriminator:
        propertyName: petType
        mapping:
          dog: Dog
          cat: "#/components/schemas/Cat"
      properties:
        petType:
          type: string
      example:
        petType: cat
        birthDate: '2000-01-01'
        huntingSkill: stealth
```

The example is on the `Pet` schema, but the warning would produce something like this:

```plain
One or more warnings exist in the OpenApi definition
  at: components > schemas > Cat > allOf > 0 > example
    Invalid value
      at: birthDate
        Property is an additional property
      at: huntingSkill
        Property is an additional property
      Did not validate against all schemas
        at: 1 > petType
          Property is an additional property
```

Also, I'd like to mention that version 2 of this library is making a lot of progress. I can add this functionality to that library without too much work and there is also significantly more control over managing errors and warnings global and on a case-by-case basis. I'm looking forward to having that complete as it will also bring browser support, TypeScript types, and more. 🎉 

After having explained the two hurdles, what thoughts do you have?

**Comment by Gi60s** [comment]
I wanted to provide a second example where I put the `example` in the `Cat` instead of the `Pet`.

```yaml
components:
  schemas:
    Cat:
      allOf:
      - "$ref": "#/components/schemas/Pet"
      - type: object
        properties:
          birthDate:
            type: string
            format: date
          huntingSkill:
            type: string
        example:
          petType: cat
          birthDate: '2000-01-01'
          huntingSkill: stealth
    Pet:
      type: object
      required:
      - petType
      discriminator:
        propertyName: petType
        mapping:
          dog: Dog
          cat: "#/components/schemas/Cat"
      properties:
        petType:
          type: string
```

Warning:

```text
One or more warnings exist in the OpenApi definition
  at: components > schemas > Cat > allOf > 1 > example
    Invalid value
      at: petType
        Property is an additional property
```
